apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: minishop
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=mssql;Database=MiniShop;User Id=sa;Password=06610661oP-;TrustServerCertificate=true"
